import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Row, Col } from "antd";
import PageContent from 'components/Layouts/page-content';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <Row gutter={[32, 32]}>
        <Col span={24}>
          <PageContent
            title="Blank Page"
            breadcrumb={[
              {
                title: "Pages",
              },
              {
                title: "Blank Page",
              }
            ]}
          />
        </Col>
      </Row>
    </div>
  )
}
